#include <stdio.h>
#include <stdlib.h>

#define MAX_DIVISORS 500
static int count_divisors(long triangle);

/**
 * The sequence of triangle numbers is generated by adding the natural numbers. So the 7th triangle number would be 1 + 2 + 3 + 4 + 5 + 6 + 7 = 28. The first ten terms would be:
 *
 * 1, 3, 6, 10, 15, 21, 28, 36, 45, 55, ...
 *
 * Let us list the factors of the first seven triangle numbers:
 * 1: 1
 * 3: 1,3
 * 6: 1,2,3,6
 * 10: 1,2,5,10
 * 15: 1,3,5,15
 * 21: 1,3,7,21
 * 28: 1,2,4,7,14,28
 *
 * We can see that 28 is the first triangle number to have over five divisors.
 * What is the value of the first triangle number to have over five hundred divisors?
 **/
void main(void) {
	long triangle, n = 1;
	while (count_divisors(triangle) < MAX_DIVISORS) {
		triangle += n++;
	}
	printf("answer: %lu \n", triangle);
}

int count_divisors(long triangle) {
	int p = 1;
	for (long n = 2; n <= triangle; n++) {
		int c = 0;
		while (triangle % n == 0) {
			c++;
			triangle /= n;
		}
		p *= c + 1;
	}
	return p;
}
