#include <stdio.h>
#define MAX_FEBO_SEQ_TERM 4000000

/**
 * Problem2
 * Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:
 * 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
 * By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.
 */
int main(void)
{
    int sum_of_febo_seq = 0;
    int idx = 1;
    while (get_fibo_seq_term(idx) < MAX_FEBO_SEQ_TERM) {
        if (get_fibo_seq_term(idx) % 2 == 0) {
            sum_of_febo_seq += get_fibo_seq_term(idx);
        }
        idx++;
    }
    printf("sum of fibonacci sequence terms whose value is even under %d: %d \n", MAX_FEBO_SEQ_TERM, sum_of_febo_seq);
    return 1;
}

/**
 * Get fibonacci sequence term
 *
 */
int get_fibo_seq_term(int idx)
{
    int first_term = 1;
    if (idx == 0 || idx == 1) {
        return first_term;
    }
    return get_fibo_seq_term(idx - 1) + get_fibo_seq_term(idx - 2);
}
