#include <stdio.h>
#define MAX_FEBO_SEQ 4000000

/**
 * Problem2
 * Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:
 * 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
 * By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.
 */
int main(void)
{
    int sum_of_fibo = 0;
    int i = 1;
    while (get_fibo_seq_term(i) < MAX_FEBO_SEQ) {
        if (get_fibo_seq_term(i) % 2 == 0) {
            sum_of_fibo += get_fibo_seq_term(i);
        }
        i++;
    }
    printf("answer: %d \n", sum_of_fibo);
    return 0;
}

/**
 * Get fibonacci sequence term
 *
 */
int get_fibo_seq_term(int i)
{
    int first_term = 1;
    if (i == 0 || i == 1) {
        return first_term;
    }
    return get_fibo_seq_term(i - 1) + get_fibo_seq_term(i - 2);
}
